name: zKoth
author: Maxlego08
main: fr.maxlego08.zkoth.ZKothPlugin
version: 2.1.4.0
softdepend: 
- PlaceholderAPI
- Guilds
- Factions
- FactionsX
- SuperiorSkyblock2
- LegacyFactions
- FeatherBoard
- TAB
- TitleManager
- UltimateFactions
- Multiverse-Core
- SternalBoard
- SimpleClan
- SternalBoard
- zSchedulers
commands:
api-version: 1.13