#########################################################################################################
#
# ███████╗██╗░░██╗░█████╗░████████╗██╗░░██╗
# ╚════██║██║░██╔╝██╔══██╗╚══██╔══╝██║░░██║
# ░░███╔═╝█████═╝░██║░░██║░░░██║░░░███████║
# ██╔══╝░░██╔═██╗░██║░░██║░░░██║░░░██╔══██║
# ███████╗██║░╚██╗╚█████╔╝░░░██║░░░██║░░██║
# ╚══════╝╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝
#
# Commands:
# /zkoth - zkoth.use - Displays the list of commands
# /zkoth reload - zkoth.reload - Reload configuration files
# /zkoth axe - zkoth.axe - Getting the selection axe
# /zkoth create <koth name> [<koth type>] [<capture/score] - zkoth.create - Create koth
# /zkoth now <koth name> - zkoth.now - Spawn a koth without cooldown
# /zkoth spawn <koth name> - zkoth.spawn - Spawn a koth
# /zkoth stop <koth name> - zkoth.stop - Stop a koth
# /zkoth move <koth name> - zkoth.stop - Move a koth
# /zkoth delete <koth name> - zkoth.delete - Delete a koth
# /zkoth version - no permission - Show plugin version
# /zkoth list - zkoth.list - Get koth list
# /zkoth loot <koth name> [<page>] - zkoth.loot - Change loot for a koth
# /zkoth addcommand <koth name> <start/win> <command> - zkoth.command.add - Add new command
#
# Placeholders:
# %zkoth_world% - Current koth world
# %zkoth_name% - Current koth name
# %zkoth_min_x% - Current koth min X
# %zkoth_min_y% - Current koth min Y
# %zkoth_min_z% - Current koth min Z
# %zkoth_max_x% - Current koth max X
# %zkoth_max_y% - Current koth max Y
# %zkoth_max_z% - Current koth max Z
# %zkoth_center_x% - Current koth center X
# %zkoth_center_y% - Current koth center Y
# %zkoth_center_z% - Current koth center Z
# %zkoth_spawn_seconds% - Current koth spawn seconds
# %zkoth_spawn_format% - Current koth spawn seconds formatted
# %zkoth_capture_seconds% - Current koth capture seconds
# %zkoth_capture_format% - Current koth capture seconds formatted
# %zkoth_capture_max_seconds% - Current koth max capture seconds
# %zkoth_capture_max_formats% - Current koth max capture seconds formatted
# %zkoth_score% - Score of player
# %zkoth_score_player_<position>% - Player name at position
# %zkoth_score_points_<position>% - Points at position
# %zkoth_score_team_name_<position>% - Team name at position
# %zkoth_score_team_id_<position>% - Team id at position
# %zkoth_score_team_leader_<position>% - Team leader name at position
# %zkoth_score_player_<position>% - Player name at position
# %zkoth_player_name% - Current koth capture player name
# %zkoth_team_name% - Current koth capture player team name
# %zkoth_team_id% - Current koth capture player team id
# %zkoth_team_leader% - Current koth capture player team leader name
# %zkoth_active_<koth name>% - Lets you know if a koth is active
# %zkoth_cooldown_<koth name>% - Lets you know if a koth is in cooldown
# %zkoth_start_<koth name>% - Lets you know if a koth is start
#
# Supported Scoreboard Plugin:
# - FeatherBoard
# - SternalBoard
# - Tab
# - TitleManager
#
# Supported Teams Plugin:
# - Lands
# - HuskTown
# - SuperiorSkyblock2
# - BetterTeams
# - SaberFaction
# - FactionUUID
# - SimpleClan
#
# Need scheduler ? Use zScheduler: https://www.spigotmc.org/resources/zschedulers.112705/
#
#########################################################################################################

# Displays more information in the console, if you have a problem please enable this option and send errors to support.
enableDebug: false

# Enables time debugs, is used to measure plugin performance
enableDebugTime: false

# Number of milliseconds between each PlayerMoveEvent action
# Allows to cooldown the player not to overload the plugin
playerMoveEventCooldown: 50

# Display a message during koth cooldown
displayMessageCooldown:
  - 300
  - 120
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

# Display a message during koth cap
displayMessageKothCap:
  - 300
  - 120
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

noPlayer: 'X'

noFaction: 'X'

noKoth: 'X'

schedulerMillisecond: 1000

removeChestSec: 120

# Value that will be used for score placeholders if the position does not exist.
defaultPlayerResult:
  playerName: "X"
  points: 0
  teamName: "X"
  teamId: "X"
  teamLeader: "X"
