#########################################################################################################
#
# ███████╗██╗░░██╗░█████╗░████████╗██╗░░██╗
# ╚════██║██║░██╔╝██╔══██╗╚══██╔══╝██║░░██║
# ░░███╔═╝█████═╝░██║░░██║░░░██║░░░███████║
# ██╔══╝░░██╔═██╗░██║░░██║░░░██║░░░██╔══██║
# ███████╗██║░╚██╗╚█████╔╝░░░██║░░░██║░░██║
# ╚══════╝╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝
#
# Commands:
# /zkoth - zkoth.use - Displays the list of commands
# /zkoth reload - zkoth.reload - Reload configuration files
# /zkoth axe - zkoth.axe - Getting the selection axe
# /zkoth create <koth name> [<koth type>] [<capture/score] - zkoth.create - Create koth
# /zkoth now <koth name> - zkoth.now - Spawn a koth without cooldown
# /zkoth spawn <koth name> - zkoth.spawn - Spawn a koth
# /zkoth stop <koth name> - zkoth.stop - Stop a koth
# /zkoth move <koth name> - zkoth.stop - Move a koth
# /zkoth delete <koth name> - zkoth.delete - Delete a koth
# /zkoth version - no permission - Show plugin version
# /zkoth list - zkoth.list - Get koth list
# /zkoth loot <koth name> [<page>] - zkoth.loot - Change loot for a koth
#
# Placeholders:
#
#
# Supported Scoreboard Plugin:
# - FeatherBoard
# - SternalBoard
# - Tab
# - TitleManager
#
#########################################################################################################

# Displays more information in the console, if you have a problem please enable this option and send errors to support.
enableDebug: false

# Enables time debugs, is used to measure plugin performance
enableDebugTime: false

# Number of milliseconds between each PlayerMoveEvent action
# Allows to cooldown the player not to overload the plugin
playerMoveEventCooldown: 50

# Display a message during koth cooldown
displayMessageCooldown:
  - 300
  - 120
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

# Display a message during koth cap
displayMessageKothCap:
  - 300
  - 120
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

noPlayer: 'X'

noFaction: 'X'

schedulerMillisecond: 1000

removeChestSec: 120