#########################################################################################################
#
# ███████╗██╗░░██╗░█████╗░████████╗██╗░░██╗
# ╚════██║██║░██╔╝██╔══██╗╚══██╔══╝██║░░██║
# ░░███╔═╝█████═╝░██║░░██║░░░██║░░░███████║
# ██╔══╝░░██╔═██╗░██║░░██║░░░██║░░░██╔══██║
# ███████╗██║░╚██╗╚█████╔╝░░░██║░░░██║░░██║
# ╚══════╝╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝
#
# Commands:
# /zkoth - zkoth.use - Displays the list of commands
# /zkoth reload - zkoth.reload - Reload configuration files
# /zkoth axe - zkoth.axe - Getting the selection axe
#
# Placeholders:
#
#
#
#########################################################################################################
